### ISSUE TITLE
How to get all genes?

### ISSUE THREAD

**Issue by ghost** [cBioPortal/cgdsr#10]
Hello, I using your package but i have some problem..
I want to extract big data including more than 10,000 genes using cdgsr::getProfileData.
what should i do if i want to extract all available genes in location "A" not inputting all gene names manually?
getProfileData(mycgds, "A", mygeneticprofile, mycaselist)

**Comment by jjgao** [comment]
@hanosng we are using [hugo gene symbols](https://www.genenames.org/download/statistics-and-files/). But our API wasn't designed to support such large query. A better option might be download our data from https://github.com/cBioPortal/datahub and process it on your end.

**Comment by ghost** [comment]
Oh thanks. I'll do your recommendation!
