### ISSUE TITLE
Issue downloading Z-scores for METABRICS data

### ISSUE THREAD

**Issue by radio1988** [cBioPortal/cgdsr#11]
Hello, I experienced some very strange with the `cgdsr` backend, because profile ‘brca_metabric_mrna_U133_Zscores’ disappeared for study ‘brca_metabric’, case ‘brca_metabric_all’, which I was able to access three weeks ago. Is there a way that I can download z-scores again to keep all my analysis consistent? Thank you so much!

## The code to get ’Z-score’ that worked before:
```
library(cgdsr)
mycgds <- CGDS("http://www.cbioportal.org/public-portal/")
studies <- getCancerStudies(mycgds)
#studies[grepl("breast invasive carcinoma", studies[, 2], ignore.case = TRUE), 1:2]
study <- "brca_metabric"
 
cases <- getCaseLists(mycgds, study)
case <- "brca_metabric_all"
 
profiles <- getGeneticProfiles(mycgds, study)
profile <- c("brca_metabric_mrna_U133_Zscores")
 
data <- getProfileData(mycgds, genes = c("SCLY"), 
                       geneticProfiles = profile,
                       caseList = case)
```
 
## The code that I use now to get log-transformed microarray intensities:
```
library(cgdsr)
mycgds <- CGDS("http://www.cbioportal.org/public-portal/")
studies <- getCancerStudies(mycgds)
#studies[grepl("breast invasive carcinoma", studies[, 2], ignore.case = TRUE), 1:2]
study <- "brca_metabric"
 
cases <- getCaseLists(mycgds, study)
case <- "brca_metabric_all"
 
profiles <- getGeneticProfiles(mycgds, study)
profile <- c("brca_metabric_rna_seq_mrna")
 
ExpData <- getProfileData(mycgds, genes = c("SCLY"), 
                       geneticProfiles = profile,
                       caseList = case)
```

**Comment by jjgao** [comment]
@radio1988 sorry for the issue. We had some problem importing the z-score profiles in the last data update (https://github.com/cBioPortal/datahub/issues/485). We are working on a fix.

**Comment by jjgao** [comment]
duplicate with https://github.com/cBioPortal/datahub/issues/485
