### ISSUE TITLE
Missing cases in TCGA-UCEC 

### ISSUE THREAD

**Issue by lucianamontivero** [cBioPortal/cgdsr#12]
Hello!

I'm trying to download the samples and RNA-Seq information from the TCGA-UCEC study with the following code: 
```
myCgds = CGDS("http://www.cbioportal.org/public-portal/")

myCancerStudy = 'ucec_tcga_pub'

myCaseList = getCaseLists(myCgds,myCancerStudy)[1,1]

myGeneticProfile = 'ucec_tcga_pub_rna_seq_v2_mrna'

myListOfGenes <- c(  'ATAD2', 'HES6')

myProfileData  <- getProfileData(myCgds, myListOfGenes, myGeneticProfile, myCaseList)

myClinicalData = getClinicalData(myCgds, myCaseList)
```

The information seems to download ok, I got the information about 232 cases, but when I checked for the same study in cBioPortal Platform, and downloaded the same information I got 333 cases.
Does anybody know why this could be happening? 

Thanks!

**Comment by jjgao** [comment]
Please select the case list `ucec_tcga_pub_rna_seq_v2_mrna` instead of the first one.

![image](https://user-images.githubusercontent.com/840895/51871999-028c7680-2326-11e9-808a-e3f756b1f019.png)

**Comment by lucianamontivero** [comment]
@jjgao Thanks! That worked perfectly
