### ISSUE TITLE
can not download adjacent normal rnaseq data

### ISSUE THREAD

**Issue by dingying85** [cBioPortal/cgdsr#19]
Hi CGDSR developer,

I find this package super useful and can easily download all tcga expression data. However, I found all the samples are tumor samples, how can I also download the adjacent normal samples for each cancer? Please advise.

Yours,
Ying Ding

**Comment by cannin** [comment]
Best to ask this question here on the Google Group: https://groups.google.com/forum/#!forum/cbioportal/join

R-specific errors are best posted here as opposed to dataset questions.
