### ISSUE TITLE
obtain the TPM unit for the RNAseq data

### ISSUE THREAD

**Issue by dingying85** [cBioPortal/cgdsr#21]
Is there a way to obtain the RNAseq expression with unit TPM?
the current one seems obtain the counts measure

**Comment by jjgao** [comment]
@dingying85 the RNAseq data in the TCGA pancan studies are batch-corrected normalized data: https://groups.google.com/forum/#!msg/cbioportal/6MZsoLeomIo/M0_9nc4AAgAJ

If you have additional questions, please feel free to contact us at cbioportal@googlegroups.com
