### ISSUE TITLE
`VITAL_STATUS` is missing

### ISSUE THREAD

**Issue by ramiromagno** [cBioPortal/cgdsr#24]
Back in July 30, 2020, the column `VITAL_STATUS` was present in the data returned by the function `cgdsr::getClinicalData`. Not anymore.

**Comment by ramiromagno** [comment]
Also, these other variables:

- `overall_survival_months`,
- `overall_survival_status`, 
- `disease_free_survival_months`, 
- `disease_free_survival_status`,
-  `age_at_diagnosis`

are mentioned in the help page of `getClinicalData()` but are not present in the output data frame.

``` r
library(cgdsr)
#> Please send questions to cbioportal@googlegroups.com
packageVersion("cgdsr")
#> [1] '1.3.0'

mycgds <- cgdsr::CGDS("https://www.cbioportal.org/")
foo <- cgdsr::getClinicalData(mycgds, caseList = "brca_tcga_pub2015_all")

"VITAL_STATUS" %in% colnames(foo)
#> [1] FALSE

c(
  "overall_survival_months",
  "overall_survival_status",
  "disease_free_survival_months",
  "disease_free_survival_status",
  "age_at_diagnosis"
) %in% colnames(foo)
#> [1] FALSE FALSE FALSE FALSE FALSE
```

<sup>Created on 2021-03-22 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by jjgao** [comment]
@ramiromagno please use `OS_STATUS`, `OS_MONTHS`, `DFS_STATUS`, `DFS_MONTHS` instead. You might also want to consider migrating to the new API and R client: https://docs.cbioportal.org/6.-web-api-and-clients/api-and-api-clients.
