### ISSUE TITLE
getClinicalData fails with blca_tcga_all: Error in scan...

### ISSUE THREAD

**Issue by rickn-horizon** [cBioPortal/cgdsr#3]
The following fails with: 

Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 284 did not have 91 elements

```R
library(cgdsr)
cbio = CGDS("http://www.cbioportal.org/")
getClinicalData(cbio, "blca_tcga_all")
```

Is it possible a comment.char="" is needed in read.table() somewhere?

**Comment by cannin** [comment]
Just committed a fix to GitHub. Check README for installing with devtools. If it works, I can deploy to CRAN.

**Comment by rickn-horizon** [comment]
That fixed it!  You rock, sir.
