### ISSUE TITLE
Pancancer download option

### ISSUE THREAD

**Issue by asmagen** [cBioPortal/cgdsr#6]
Hello,

Is there any way to download pan cancer data and not repeat the download for each tissue individually? Something like supplying multiple cancer study parameters in one function call.

Thanks

**Comment by jjgao** [comment]
@asmagen you might want to try out our new API (http://www.cbioportal.org/api/swagger-ui.html#/Molecular_Data). You can generate R, Python and other clients to access it: https://swagger.io/tools/swagger-codegen/.
