### ISSUE TITLE
There are no-matching genes

### ISSUE THREAD

**Issue by ghost** [cBioPortal/cgdsr#8]
I'm 'cgdsr' user and want to extract data using your package.
However I found strange problem.
My codes are below:

mycgds = CGDS("http://www.cbioportal.org/public-portal/")
cancerstudy <- getCancerStudies(mycgds)
mystudy <- cancerstudy[12,1]
mygeneticprofile <- getGeneticProfiles(mycgds,mystudy)[7,1]
mycaselist <- getCaseLists(mycgds,mystudy)[6,1]

head(getProfileData(mycgds, "AACSL", mygeneticprofile, mycaselist))
head(getProfileData(mycgds, "A2BP1", mygeneticprofile, mycaselist))

Here is the thing.
As you can see in the attached photo, the name of the gene I entered does not match the name of the resulting gene.
![capture](https://user-images.githubusercontent.com/45118748/48673945-61957880-eb8a-11e8-9a22-493d009db3c7.PNG)

If you know the cause of the problem or know the solution, I would appreciate your help.

Thanks & best regards.

**Comment by jjgao** [comment]
@hanosng : that's because AACSL and A2BP1 are legacy gene symbols and their new Hugo symbols are AACSP1 and RBFOX1.

https://www.genecards.org/cgi-bin/carddisp.pl?gene=AACSL
https://www.genecards.org/cgi-bin/carddisp.pl?gene=A2BP1

**Comment by ghost** [comment]
I unterstand, Thanks for your rely!
